server:
  port: 9200
  compression:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    base-dir: .
    connection-timeout: 1000
    accept-count: 100
    threads:
      min-spare: 20
      max: 500
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_mate?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    root: INFO